#!/bin/bash
set -eu

if [ "$#" != 2 ]; then
    echo >&2 "Usage: $0 <clone_url> <public_username>

A VERY SLOW mining implementation. This should give you an idea of
where to start, but it probably won't successfully mine you any
Gitcoins.

Arguments:

<clone_url> is the string you'd pass to git clone (i.e.
  something of the form username@hostname:path)

<public_username> is the public username provided to you in
  the CTF web interface."
    exit 1
fi

export clone_spec=$1
export public_username=$2

prepare_index() {
    perl -i -pe 's/($ENV{public_username}: )(\d+)/$1 . ($2+1)/e' LEDGER.txt
    grep -q "$public_username" LEDGER.txt || echo "$public_username: 1" >> LEDGER.txt

    git add LEDGER.txt
}

solve() {
    # Brute force until you find something that's lexicographically
    # small than $difficulty.
    difficulty=$(cat difficulty.txt)

    # Create a Git tree object reflecting our current working
    # directory
    tree=$(git write-tree)
    parent=$(git rev-parse HEAD)
    timestamp=$(date +%s)


	body="tree $tree\nparent $parent\nauthor CTF user <me@example.com> $timestamp +0000\ncommitter CTF user <me@example.com> $timestamp +0000\nGive me a Gitcoin\n"

	# See http://git-scm.com/book/en/Git-Internals-Git-Objects for
	# details on Git objects.
	new_body="$( echo $body | /root/projects/level1/dumb $difficulty | tee text.txt)"
	sha1=$(cat test.txt | git hash-object -t commit --stdin)
	echo "Mined a Gitcoin with commit: $sha1"
	cat test.txt | git hash-object -w -t commit --stdin > /dev/null
	git reset --hard "$sha1" > /dev/null
}

reset() {
    git fetch origin master >/dev/null 2>/dev/null
    git reset --hard origin/master >/dev/null
}

# Set up repo
local_path=./${clone_spec##*:}

if [ -d "$local_path" ]; then
    echo "Using existing repository at $local_path"
    cd "$local_path"
else
    echo "Cloning repository to $local_path"
    git clone "$clone_spec" "$local_path"
    cd "$local_path"
fi

while true; do
   # reset
    prepare_index
    solve
    echo "testing"
    if git push origin master; then
	echo "Success :)"
	break
    else
	echo "Starting over :("
	reset
    fi
done
